FROM node:20-slim

WORKDIR /app

RUN apt-get update && \
    apt-get install -y yt-dlp ffmpeg && \
    apt-get clean && \
    rm -rf /var/lib/apt/lists/*

COPY package*.json ./
RUN npm install --omit=dev

COPY . .

COPY cookies.txt /app/cookies.txt
RUN mkdir -p /app/downloads

EXPOSE 3000

CMD ["node", "index.js"]